# Generated by Django 4.2.16 on 2024-10-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.company'),
        ),
    ]
